[tool.black]
line_length = 119
skip_string_normalization = true
required_version = "24"
target-version = ['py310', 'py311', 'py312']
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^\/useless_package\/
)
'''
