name: Black (python)
# Solution from https://stackoverflow.com/a/72088304

on:
  pull_request:
    branches:
      - main

jobs:
  reformat_with_black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # https://github.com/tj-actions/changed-files
        with:
          files: |
            **.py

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            echo "$file was changed"
          done

      - name: Setup Python env
        uses: actions/setup-python@v3

      - name: Install black
        run: pip install black~=24.1

      - name: Apply black only to changed files
        run: |
          black ${{ steps.changed-files.outputs.all_changed_files }}
