name: CI-Import-Check

on:
  push:
  pull_request:
    paths:
      - "**"

# Check https://hub.docker.com/r/pytorch/pytorch/tags for latest tags
jobs:

  flake8:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install flake8
        run:  |
          pip install flake8
      - name: run flake8
        run: |
          flake8 .
